# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20180125_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='after_success_closing_order_message',
            field=models.TextField(blank=True, default='', help_text='Если вы оставите сообщение пустым, то будет использоваться глобальный шаблон из глобальных настроек.<br/><div class="variablesHint">Доступные переменные:<br/><br/><span class="variable">{{first_name}}</span> &mdash; <span class="helpText">Иван</span><br/><span class="variable">{{last_name}}</span> &mdash; <span class="helpText">Иванович</span><br/><span class="variable">{{middle_name}}</span> &mdash; <span class="helpText">Иванов</span><br/><span class="variable">{{full_name}}</span> &mdash; <span class="helpText">Иван Иванович</span><br/><span class="variable">{{site}}</span> &mdash; <span class="helpText">example.com.</span><br/><div>', max_length=3200, null=True, verbose_name='Сообщение после смена статуса заказа на «Успешно Завершён»'),
        ),
        migrations.AddField(
            model_name='order',
            name='after_success_closing_order_subject',
            field=models.CharField(blank=True, default='', help_text='Если вы не определите тему сообщения, то будет использоваться глобальный шаблон из глобальных настроек.<br/><div class="variablesHint">Доступные переменные:<br/><br/><span class="variable">{{first_name}}</span> &mdash; <span class="helpText">Иван</span><br/><span class="variable">{{last_name}}</span> &mdash; <span class="helpText">Иванович</span><br/><span class="variable">{{middle_name}}</span> &mdash; <span class="helpText">Иванов</span><br/><span class="variable">{{full_name}}</span> &mdash; <span class="helpText">Иван Иванович</span><br/><span class="variable">{{site}}</span> &mdash; <span class="helpText">example.com.</span><br/><div>', max_length=200, null=True, verbose_name='Тема сообщения после смена статуса заказа на «Успешно Завершён»'),
        ),
        migrations.AddField(
            model_name='order',
            name='change_status_order_in_process_message',
            field=models.TextField(blank=True, default='', help_text='Если вы оставите сообщение пустым, то будет использоваться глобальный шаблон из глобальных настроек.<br/><div class="variablesHint">Доступные переменные:<br/><br/><span class="variable">{{first_name}}</span> &mdash; <span class="helpText">Иван</span><br/><span class="variable">{{last_name}}</span> &mdash; <span class="helpText">Иванович</span><br/><span class="variable">{{middle_name}}</span> &mdash; <span class="helpText">Иванов</span><br/><span class="variable">{{full_name}}</span> &mdash; <span class="helpText">Иван Иванович</span><br/><span class="variable">{{site}}</span> &mdash; <span class="helpText">example.com.</span><br/><div>', max_length=3200, null=True, verbose_name='Сообщение, после смена статуса заказа на «В процессе»'),
        ),
        migrations.AddField(
            model_name='order',
            name='change_status_order_in_process_subject',
            field=models.CharField(blank=True, default='', help_text='Если вы не определите тему сообщения, то будет использоваться глобальный шаблон из глобальных настроек.<br/><div class="variablesHint">Доступные переменные:<br/><br/><span class="variable">{{first_name}}</span> &mdash; <span class="helpText">Иван</span><br/><span class="variable">{{last_name}}</span> &mdash; <span class="helpText">Иванович</span><br/><span class="variable">{{middle_name}}</span> &mdash; <span class="helpText">Иванов</span><br/><span class="variable">{{full_name}}</span> &mdash; <span class="helpText">Иван Иванович</span><br/><span class="variable">{{site}}</span> &mdash; <span class="helpText">example.com.</span><br/><div>', max_length=200, null=True, verbose_name='Тема сообщения, после смена статуса заказа на «В процессе»'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=36, null=True, unique=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('В процессе', 'В процессе'), ('Успешно завершён', 'Успешно завершён'), ('Архивирован', 'Архивирован')], default='Новый', help_text='При смене статуса на "В процессе" или на "Успешно завершён" заказчику отправляется сообщение указанное в "Настройках".', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
