# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20180208_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='after_success_closing_order_message',
            field=models.TextField(blank=True, default='', help_text='Если вы оставите сообщение пустым, то будет использоваться глобальный шаблон из глобальных настроек.<br/><div class="variablesHint">Доступные переменные:<br/><br/><span class="variable">{{first_name}}</span> &mdash; <span class="helpText">Иван</span><br/><span class="variable">{{last_name}}</span> &mdash; <span class="helpText">Иванович</span><br/><span class="variable">{{middle_name}}</span> &mdash; <span class="helpText">Иванов</span><br/><span class="variable">{{full_name}}</span> &mdash; <span class="helpText">Иван Иванович</span><br/><span class="variable">{{site}}</span> &mdash; <span class="helpText">artceiling-systems.ru.</span><br/><span class="variable">{{phone_number}}</span> &mdash; <span class="helpText">Телефон заказчика(Может отсутствовать)</span><br/><span class="variable">{{email}}</span> &mdash; <span class="helpText">Email заказчика(Может отсутствовать)</span><br/><div>', max_length=3200, null=True, verbose_name='Сообщение после смена статуса заказа на «Успешно Завершён»'),
        ),
        migrations.AlterField(
            model_name='order',
            name='after_success_closing_order_subject',
            field=models.CharField(blank=True, default='', help_text='Если вы не определите тему сообщения, то будет использоваться глобальный шаблон из глобальных настроек.<br/><div class="variablesHint">Доступные переменные:<br/><br/><span class="variable">{{first_name}}</span> &mdash; <span class="helpText">Иван</span><br/><span class="variable">{{last_name}}</span> &mdash; <span class="helpText">Иванович</span><br/><span class="variable">{{middle_name}}</span> &mdash; <span class="helpText">Иванов</span><br/><span class="variable">{{full_name}}</span> &mdash; <span class="helpText">Иван Иванович</span><br/><span class="variable">{{site}}</span> &mdash; <span class="helpText">artceiling-systems.ru.</span><br/><span class="variable">{{phone_number}}</span> &mdash; <span class="helpText">Телефон заказчика(Может отсутствовать)</span><br/><span class="variable">{{email}}</span> &mdash; <span class="helpText">Email заказчика(Может отсутствовать)</span><br/><div>', max_length=200, null=True, verbose_name='Тема сообщения после смена статуса заказа на «Успешно Завершён»'),
        ),
        migrations.AlterField(
            model_name='order',
            name='change_status_order_in_process_message',
            field=models.TextField(blank=True, default='', help_text='Если вы оставите сообщение пустым, то будет использоваться глобальный шаблон из глобальных настроек.<br/><div class="variablesHint">Доступные переменные:<br/><br/><span class="variable">{{first_name}}</span> &mdash; <span class="helpText">Иван</span><br/><span class="variable">{{last_name}}</span> &mdash; <span class="helpText">Иванович</span><br/><span class="variable">{{middle_name}}</span> &mdash; <span class="helpText">Иванов</span><br/><span class="variable">{{full_name}}</span> &mdash; <span class="helpText">Иван Иванович</span><br/><span class="variable">{{site}}</span> &mdash; <span class="helpText">artceiling-systems.ru.</span><br/><span class="variable">{{phone_number}}</span> &mdash; <span class="helpText">Телефон заказчика(Может отсутствовать)</span><br/><span class="variable">{{email}}</span> &mdash; <span class="helpText">Email заказчика(Может отсутствовать)</span><br/><div>', max_length=3200, null=True, verbose_name='Сообщение, после смена статуса заказа на «В процессе»'),
        ),
        migrations.AlterField(
            model_name='order',
            name='change_status_order_in_process_subject',
            field=models.CharField(blank=True, default='', help_text='Если вы не определите тему сообщения, то будет использоваться глобальный шаблон из глобальных настроек.<br/><div class="variablesHint">Доступные переменные:<br/><br/><span class="variable">{{first_name}}</span> &mdash; <span class="helpText">Иван</span><br/><span class="variable">{{last_name}}</span> &mdash; <span class="helpText">Иванович</span><br/><span class="variable">{{middle_name}}</span> &mdash; <span class="helpText">Иванов</span><br/><span class="variable">{{full_name}}</span> &mdash; <span class="helpText">Иван Иванович</span><br/><span class="variable">{{site}}</span> &mdash; <span class="helpText">artceiling-systems.ru.</span><br/><span class="variable">{{phone_number}}</span> &mdash; <span class="helpText">Телефон заказчика(Может отсутствовать)</span><br/><span class="variable">{{email}}</span> &mdash; <span class="helpText">Email заказчика(Может отсутствовать)</span><br/><div>', max_length=200, null=True, verbose_name='Тема сообщения, после смена статуса заказа на «В процессе»'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, help_text='<div class="variablesHint">Доступные переменные:<br/><br/><span class="variable">{{first_name}}</span> &mdash; <span class="helpText">Иван</span><br/><span class="variable">{{last_name}}</span> &mdash; <span class="helpText">Иванович</span><br/><span class="variable">{{middle_name}}</span> &mdash; <span class="helpText">Иванов</span><br/><span class="variable">{{full_name}}</span> &mdash; <span class="helpText">Иван Иванович</span><br/><span class="variable">{{site}}</span> &mdash; <span class="helpText">artceiling-systems.ru.</span><br/><span class="variable">{{phone_number}}</span> &mdash; <span class="helpText">Телефон заказчика(Может отсутствовать)</span><br/><span class="variable">{{email}}</span> &mdash; <span class="helpText">Email заказчика(Может отсутствовать)</span><br/><span class="variable">{{question}}</span> &mdash; <span class="helpText">Вопрос заказчика</span><br/><div>', max_length=1000, null=True, verbose_name='Ответ на вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_subject',
            field=models.CharField(blank=True, help_text='<div class="variablesHint">Доступные переменные:<br/><br/><span class="variable">{{first_name}}</span> &mdash; <span class="helpText">Иван</span><br/><span class="variable">{{last_name}}</span> &mdash; <span class="helpText">Иванович</span><br/><span class="variable">{{middle_name}}</span> &mdash; <span class="helpText">Иванов</span><br/><span class="variable">{{full_name}}</span> &mdash; <span class="helpText">Иван Иванович</span><br/><span class="variable">{{site}}</span> &mdash; <span class="helpText">artceiling-systems.ru.</span><br/><span class="variable">{{phone_number}}</span> &mdash; <span class="helpText">Телефон заказчика(Может отсутствовать)</span><br/><span class="variable">{{email}}</span> &mdash; <span class="helpText">Email заказчика(Может отсутствовать)</span><br/><div>', max_length=150, null=True, verbose_name='Тема email сообщения'),
        ),
    ]
