# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180208_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='meta',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Глобальное мето описание'),
        ),
    ]
