# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_proportion'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='is_tests_included',
            field=models.BooleanField(default=False, verbose_name='Включить front-end тесты?'),
        ),
        migrations.AddField(
            model_name='settings',
            name='tests_file_name',
            field=models.TextField(blank=True, help_text='Пример: tests.hashname.js', max_length=100, null=True, verbose_name='Имя файла тестов'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='meta',
            field=models.TextField(blank=True, help_text='Для каждый страницы делать лучше уникальное описание.', max_length=300, null=True, verbose_name='Глобальное мета описание'),
        ),
    ]
