# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180524_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='tests_file_name',
            field=models.CharField(blank=True, help_text='Пример: tests.hashname.js', max_length=100, null=True, verbose_name='Имя файла тестов'),
        ),
    ]
