# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180524_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='is_send_sms',
            field=models.BooleanField(default=True, verbose_name='Включить смс оповещения?'),
        ),
    ]
