# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_settings_is_send_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='email_recipients',
            field=models.TextField(blank=True, help_text='Пример: shiningfinger@list.ru, g_zhur@ortgraph.ru, awesome@ceiling.com', max_length=2048, null=True, verbose_name='Список получателей email сообщний'),
        ),
    ]
