
export const OPEN_CALLBACK = 'OPEN_CALLBACK';
export const ORDER_CALLBACK = 'ORDER_CALLBACK';
export const CLOSE_CALLBACK = 'CLOSE_CALLBACK';
export const REQUEST_CALLBACK = 'REQUEST_CALLBACK';
export const ASK_QUESTION = 'ASK_QUESTION';
