export const REQUEST_CATALOG = 'REQUEST_CATALOG';
export const RETRIEVE_CATEGORY = 'RETRIEVE_CATEGORY';
export const RETRIEVE_CATALOG = 'RETRIEVE_CATALOG';
export const RETRIEVE_SINGLE_PRODUCT = 'RETRIEVE_SINGLE_PRODUCT';
export const RETRIEVE_COLLECTION = 'RETRIEVE_COLLECTION';
export const RETRIEVE_BRAND = 'RETRIEVE_BRAND';
export const REFETCH_DATA = 'REFETCH_DATA';

export const CATEGORY = 'CATEGORY';
export const PRODUCT = 'PRODUCT';
export const COLLECTION = 'COLLECTION';
export const BRAND = 'BRAND';
export const CATALOG = 'BRAND';
