# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-13 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('utm_content', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Дополнительная информация, которая помогает различать объявления;')),
                ('utm_source', models.CharField(default='', max_length=200, verbose_name='Источник перехода')),
                ('utm_campaign', models.CharField(default='', max_length=200, verbose_name='Название рекламной кампании')),
                ('utm_medium', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Тип трафика')),
                ('utm_term', models.CharField(default='', max_length=200, verbose_name='Тип трафика')),
            ],
            options={
                'verbose_name': 'UTM Метка',
                'verbose_name_plural': 'UTM Метки',
                'db_table': 'cosmeticsyou_advertising_utm_marks',
            },
        ),
    ]
