# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-05-12 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('page_title', models.CharField(blank=True, help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u043e \u0432\u043a\u043b\u0430\u0434\u043a\u0435', max_length=100, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('meta', models.TextField(blank=True, max_length=300, null=True, verbose_name='META-\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
                ('brands', models.ManyToManyField(blank=True, help_text='\u0411\u0440\u0435\u043d\u0434\u044b, \u043a\u043e\u0442\u043e\u0440\u044b\u0435 \u0431\u0443\u0434\u0443\u0442 \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c\u0441\u044f \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435 "\u0410\u043a\u0446\u0438\u0438".', related_name='brands_of_catalog', to='catalog.Brand', verbose_name='\u0411\u0440\u0435\u043d\u0434\u044b \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0430')),
                ('categories', models.ManyToManyField(blank=True, help_text='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438, \u043a\u043e\u0442\u043e\u0440\u044b\u0435 \u0431\u0443\u0434\u0443\u0442 \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c\u0441\u044f \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435 "\u0410\u043a\u0446\u0438\u0438".', related_name='categories_of_catalog_page', to='catalog.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0430')),
            ],
            options={
                'db_table': 'data_catalog_page',
                'verbose_name': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 "\u041a\u0430\u0442\u0430\u043b\u043e\u0433"',
                'verbose_name_plural': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 "\u041a\u0430\u0442\u0430\u043b\u043e\u0433"',
            },
        ),
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('page_title', models.CharField(blank=True, help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u043e \u0432\u043a\u043b\u0430\u0434\u043a\u0435', max_length=100, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('meta', models.TextField(blank=True, max_length=300, null=True, verbose_name='META-\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
                ('map', models.TextField(blank=True, default=b'<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2243.346384211085!2d37.66873831593188!3d55.78722298056262!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46b53584d0651261%3A0xba525273abdde888!2z0YPQuy4g0KjRg9C80LrQuNC90LAsIDIw0YExLCDQnNC-0YHQutCy0LAsIDEwNzExMw!5e0!3m2!1sru!2sru!4v1516777576394" width="100%" frameborder="0" style="border:0" allowfullscreen></iframe>', help_text='\u041a\u0430\u0440\u0442\u0430, \u043a\u043e\u0442\u043e\u0440\u0430\u044f \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0435\u0442\u0441\u044f \u0432 \u043a\u043e\u043d\u0442\u0430\u043a\u0442\u0430\u0445', max_length=2048, null=True, verbose_name='\u041e\u043a\u043d\u043e \u0441 \u043a\u0430\u0440\u0442\u043e\u0439')),
            ],
            options={
                'db_table': 'data_contacts_page',
                'verbose_name': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 "\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b"',
                'verbose_name_plural': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 "\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b"',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('page_title', models.CharField(blank=True, help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u043e \u0432\u043a\u043b\u0430\u0434\u043a\u0435', max_length=100, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('meta', models.TextField(blank=True, max_length=300, null=True, verbose_name='META-\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
                ('brands', models.ManyToManyField(blank=True, related_name='brands_of_home_page', to='catalog.Brand', verbose_name='\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0435\u043c\u044b\u0435 \u0431\u0440\u0435\u043d\u0434\u044b')),
            ],
            options={
                'db_table': 'data_home_page',
                'verbose_name': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 "\u0413\u043b\u0430\u0432\u043d\u0430\u044f"',
                'verbose_name_plural': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 "\u0413\u043b\u0430\u0432\u043d\u0430\u044f"',
            },
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('page_title', models.CharField(blank=True, help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u043e \u0432\u043a\u043b\u0430\u0434\u043a\u0435', max_length=100, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('meta', models.TextField(blank=True, max_length=300, null=True, verbose_name='META-\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
            ],
            options={
                'db_table': 'data_service_page',
                'verbose_name': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 "\u0421\u0435\u0440\u0432\u0438\u0441"',
                'verbose_name_plural': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 "\u0421\u0435\u0440\u0432\u0438\u0441"',
            },
        ),
    ]
