# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20180208_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicepage',
            options={'verbose_name': 'Страница "Сервис"', 'verbose_name_plural': 'Страница "Сервис"'},
        ),
    ]
