# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-05-12 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import pages.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('page_title', models.CharField(blank=True, help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u043e \u0432\u043a\u043b\u0430\u0434\u043a\u0435', max_length=100, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('meta', models.TextField(blank=True, max_length=350, null=True, verbose_name='META-\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('description', models.TextField(blank=True, max_length=650, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('slogan', models.CharField(blank=True, help_text="\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043e\u0441\u043e\u0431\u0435\u043d\u043d\u043e\u0441\u0442\u0435\u0439. \u041a \u043f\u0440\u0438\u043c\u0435\u0440\u0443, \u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435: '\u0410\u043b\u044e\u043c\u0438\u043d\u0438\u0439', \u0421\u043b\u043e\u0433\u0430\u043d: '13-\u0439 \u044d\u043b\u0435\u043c\u0435\u043d\u0442 \u0442\u0430\u0431\u043b\u0438\u0446\u044b \u043c\u0435\u043d\u0434\u0435\u043b\u0435\u0435\u0432\u0430'", max_length=150, null=True, verbose_name='\u0421\u043b\u043e\u0433\u0430\u043d')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440')),
                ('slug', models.SlugField(default=uuid.uuid1, help_text='\u041a \u043f\u0440\u0438\u043c\u0435\u0440\u0443, "new-awesome_collection-2018"', max_length=150, unique=True, validators=[pages.validators.validate_slug_field], verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('is_shown', models.BooleanField(default=True, verbose_name='\u041e\u0442\u043e\u0431\u0440\u0437\u0438\u0442\u044c \u0432 \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0435?')),
            ],
            options={
                'db_table': 'brands_of_catalog',
                'verbose_name': '\u0411\u0440\u0435\u043d\u0434',
                'verbose_name_plural': '\u0411\u0440\u0435\u043d\u0434\u044b',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('page_title', models.CharField(blank=True, help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u043e \u0432\u043a\u043b\u0430\u0434\u043a\u0435', max_length=100, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('meta', models.TextField(blank=True, max_length=350, null=True, verbose_name='META-\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('description', models.TextField(blank=True, max_length=650, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('slogan', models.CharField(blank=True, help_text="\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043e\u0441\u043e\u0431\u0435\u043d\u043d\u043e\u0441\u0442\u0435\u0439. \u041a \u043f\u0440\u0438\u043c\u0435\u0440\u0443, \u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435: '\u0410\u043b\u044e\u043c\u0438\u043d\u0438\u0439', \u0421\u043b\u043e\u0433\u0430\u043d: '13-\u0439 \u044d\u043b\u0435\u043c\u0435\u043d\u0442 \u0442\u0430\u0431\u043b\u0438\u0446\u044b \u043c\u0435\u043d\u0434\u0435\u043b\u0435\u0435\u0432\u0430'", max_length=150, null=True, verbose_name='\u0421\u043b\u043e\u0433\u0430\u043d')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440')),
                ('slug', models.SlugField(default=uuid.uuid1, help_text='\u041a \u043f\u0440\u0438\u043c\u0435\u0440\u0443, "new-awesome_collection-2018"', max_length=150, unique=True, validators=[pages.validators.validate_slug_field], verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('is_shown', models.BooleanField(default=True, verbose_name='\u041e\u0442\u043e\u0431\u0440\u0437\u0438\u0442\u044c \u0432 \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0435?')),
                ('brands', models.ManyToManyField(blank=True, help_text='\u0412\u044b\u0431\u0438\u0440\u0435\u0442\u0435 \u0431\u0440\u0435\u043d\u0434\u044b, \u043a\u043e\u0442\u043e\u0440\u044b\u0435 \u0431\u0443\u0434\u0443\u0442 \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c\u0441\u044f \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435 \u0432\u044b\u0431\u0440\u0430\u043d\u043d\u043e\u0439 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u043c \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438.', related_name='brands_of_category', to='catalog.Brand', verbose_name='\u0411\u0440\u0435\u043d\u0434\u044b \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438')),
            ],
            options={
                'db_table': 'categories_of_catalog',
                'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f',
                'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='CategorySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('section_name', models.CharField(max_length=150, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'db_table': 'section_of_category',
                'verbose_name': '\u0421\u0435\u043a\u0446\u0438\u044f',
                'verbose_name_plural': '\u0421\u0435\u043a\u0446\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('page_title', models.CharField(blank=True, help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u043e \u0432\u043a\u043b\u0430\u0434\u043a\u0435', max_length=100, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('meta', models.TextField(blank=True, max_length=350, null=True, verbose_name='META-\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('description', models.TextField(blank=True, max_length=650, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('slogan', models.CharField(blank=True, help_text="\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043e\u0441\u043e\u0431\u0435\u043d\u043d\u043e\u0441\u0442\u0435\u0439. \u041a \u043f\u0440\u0438\u043c\u0435\u0440\u0443, \u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435: '\u0410\u043b\u044e\u043c\u0438\u043d\u0438\u0439', \u0421\u043b\u043e\u0433\u0430\u043d: '13-\u0439 \u044d\u043b\u0435\u043c\u0435\u043d\u0442 \u0442\u0430\u0431\u043b\u0438\u0446\u044b \u043c\u0435\u043d\u0434\u0435\u043b\u0435\u0435\u0432\u0430'", max_length=150, null=True, verbose_name='\u0421\u043b\u043e\u0433\u0430\u043d')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440')),
                ('slug', models.SlugField(default=uuid.uuid1, help_text='\u041a \u043f\u0440\u0438\u043c\u0435\u0440\u0443, "new-awesome_collection-2018"', max_length=150, unique=True, validators=[pages.validators.validate_slug_field], verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('is_shown', models.BooleanField(default=True, verbose_name='\u041e\u0442\u043e\u0431\u0440\u0437\u0438\u0442\u044c \u0432 \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0435?')),
                ('brand', models.ForeignKey(blank=True, help_text='\u0412\u044b\u0431\u0438\u0440\u0435\u0442\u0435 \u0431\u0440\u0435\u043d\u0434, \u043a\u043e\u0442\u043e\u0440\u044b\u0439 \u043e\u0442\u043d\u043e\u0441\u0438\u0442\u0441\u044f \u043a \u044d\u0442\u043e\u0439 \u043a\u043e\u043b\u043b\u0435\u043a\u0446\u0438\u0438. \u041e\u043d\u0430 \u043c\u043e\u0436\u0435\u0442 \u0431\u044b\u0442\u044c \u043d\u0435\u0437\u0430\u0432\u0438\u0441\u0438\u043c\u043e\u0439.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_of_collection', to='catalog.Brand', verbose_name='\u0411\u0440\u0435\u043d\u0434 \u043a\u043e\u043b\u043b\u0435\u043a\u0446\u0438\u0438')),
                ('category', models.ForeignKey(blank=True, help_text='\u0412\u044b\u0431\u0438\u0440\u0435\u0442\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044e, \u043a \u043a\u043e\u0442\u043e\u0440\u044b\u0439 \u043e\u0442\u043d\u043e\u0441\u0438\u0442\u0441\u044f \u044d\u0442\u0430 \u043a\u043e\u043b\u043b\u0435\u043a\u0446\u0438\u044f.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_of_collection', to='catalog.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u043a\u043e\u043b\u043b\u0435\u043a\u0446\u0438\u0438')),
            ],
            options={
                'db_table': 'collections_of_brand',
                'verbose_name': '\u041a\u043e\u043b\u043b\u0435\u043a\u0446\u0438\u044f',
                'verbose_name_plural': '\u041a\u043e\u043b\u043b\u0435\u043a\u0446\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('width', models.CharField(blank=True, help_text='\u041f\u0440\u0438\u043c\u0435\u0440: \u041e\u0442 10 \u043c\u043c \u0434\u043e 250 \u043c\u043c', max_length=100, null=True, verbose_name='\u0428\u0438\u0440\u0438\u043d\u0430')),
                ('height', models.CharField(blank=True, help_text='\u041f\u0440\u0438\u043c\u0435\u0440: 8\u043c\u043c', max_length=100, null=True, verbose_name='\u0412\u044b\u0441\u043e\u0442\u0430')),
                ('length', models.CharField(blank=True, help_text='\u041f\u0440\u0438\u043c\u0435\u0440: \u043e\u0442 1\u043c \u0434\u043e 10\u043c', max_length=100, null=True, verbose_name='\u0414\u043b\u0438\u043d\u0430')),
                ('thickness', models.CharField(blank=True, help_text='\u041f\u0440\u0438\u043c\u0435\u0440: \u043e\u0442 1 \u043c\u043c \u0434\u043e 1,5 \u043c\u043c', max_length=100, null=True, verbose_name='\u0422\u043e\u043b\u0449\u0438\u043d\u0430')),
                ('step_between_panels', models.CharField(blank=True, help_text='\u041f\u0440\u0438\u043c\u0435\u0440: \u043e\u0442 100 \u043c\u043c \u0434\u043e 1000 \u043c\u043c', max_length=100, null=True, verbose_name='\u0428\u0430\u0433 \u043c\u0435\u0436\u0434\u0443 \u043f\u0430\u043d\u0435\u043b\u044f\u043c\u0438')),
                ('angle_of_bend', models.IntegerField(blank=True, help_text='\u0426\u0435\u043b\u043e\u0447\u0438\u0441\u043b\u0435\u043d\u043d\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435, \u043a \u043f\u0440\u0438\u043c\u0435\u0440\u0443: 30', null=True, verbose_name='\u041c\u0438\u043d\u0438\u043c\u0430\u043b\u044c\u043d\u044b\u0439 \u0443\u0433\u043e\u043b \u0437\u0430\u0433\u0438\u0431\u0430')),
                ('diameter', models.CharField(blank=True, help_text='\u041f\u0440\u0438\u043c\u0435\u0440: \u043e\u0442 50 \u043c\u043c \u0434\u043e 150 \u043c\u043c', max_length=100, null=True, verbose_name='\u0414\u0438\u0430\u043c\u0435\u0442\u0440 \u043e\u043a\u0440\u0443\u0436\u043d\u043e\u0441\u0442\u0438')),
                ('ceil_size', models.CharField(blank=True, help_text='\u041f\u0440\u0438\u043c\u0435\u0440: \u043e\u0442 5\u043c\u043c \u0434\u043e 50 \u043c\u043c', max_length=100, null=True, verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440 \u044f\u0447\u0435\u0435\u043a')),
                ('page_title', models.CharField(blank=True, help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u043e \u0432\u043a\u043b\u0430\u0434\u043a\u0435', max_length=100, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('is_shown', models.BooleanField(default=True, verbose_name='\u041e\u0442\u043e\u0431\u0440\u0437\u0438\u0442\u044c \u0432 \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0435?')),
                ('meta', models.TextField(blank=True, max_length=350, null=True, verbose_name='META-\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('description', models.TextField(blank=True, max_length=650, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('slogan', models.CharField(blank=True, help_text="\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043e\u0441\u043e\u0431\u0435\u043d\u043d\u043e\u0441\u0442\u0435\u0439. \u041a \u043f\u0440\u0438\u043c\u0435\u0440\u0443, \u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435: '\u0410\u043b\u044e\u043c\u0438\u043d\u0438\u0439', \u0421\u043b\u043e\u0433\u0430\u043d: '13-\u0439 \u044d\u043b\u0435\u043c\u0435\u043d\u0442 \u0442\u0430\u0431\u043b\u0438\u0446\u044b \u043c\u0435\u043d\u0434\u0435\u043b\u0435\u0435\u0432\u0430'", max_length=150, null=True, verbose_name='\u0421\u043b\u043e\u0433\u0430\u043d')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u0448\u0442\u0443\u043a\u0443')),
                ('currency', models.CharField(blank=True, choices=[(b'\xe2\x82\xbd', b'\xe2\x82\xbd'), (b'\xe2\x82\xac', b'\xe2\x82\xac'), (b'$', b'$')], default=b'\xe2\x82\xbd', max_length=20, null=True, verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440')),
                ('slug', models.SlugField(default=uuid.uuid1, help_text='\u041a \u043f\u0440\u0438\u043c\u0435\u0440\u0443, "new-awesome_collection-2018"', max_length=150, unique=True, validators=[pages.validators.validate_slug_field], verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('content', models.TextField(blank=True, max_length=8164, null=True, verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439 \u043a\u043e\u043d\u0442\u0435\u043d\u0442')),
                ('acoustics', models.ManyToManyField(blank=True, to='home.Acoustics', verbose_name='\u0410\u043a\u0443\u0441\u0442\u0438\u043a\u0430')),
                ('album', models.ForeignKey(blank=True, help_text='\u0410\u043b\u044c\u0431\u043e\u043c \u0434\u043b\u044f \u0441\u043b\u0430\u0439\u0434\u043e\u0432.', null=True, on_delete=django.db.models.deletion.CASCADE, to='album.Album', verbose_name='\u041f\u0440\u0435\u0437\u0435\u043d\u0442\u0430\u0446\u0438\u043e\u043d\u043d\u044b\u0439 \u0430\u043b\u044c\u0431\u043e\u043c')),
                ('brand', models.ForeignKey(blank=True, help_text='\u0412\u044b\u0431\u0438\u0440\u0435\u0442\u0435 \u0431\u0440\u0435\u043d\u0434, \u043a\u043e\u0442\u043e\u0440\u044b\u0439 \u043e\u0442\u043d\u043e\u0441\u0438\u0442\u0441\u044f \u043a \u044d\u0442\u043e\u043c\u0443 \u043e\u0431\u0440\u0430\u0437\u0446\u0443.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_of_product', to='catalog.Brand', verbose_name='\u0411\u0440\u0435\u043d\u0434 \u043e\u0431\u0440\u0430\u0437\u0446\u0430')),
                ('colors', models.ManyToManyField(blank=True, to='home.Color', verbose_name='\u0426\u0432\u0435\u0442')),
                ('combustibility', models.ManyToManyField(blank=True, to='home.Combustibility', verbose_name='\u0413\u043e\u0440\u044e\u0447\u0435\u0441\u0442\u044c')),
                ('edges', models.ManyToManyField(blank=True, to='home.Edge', verbose_name='\u041a\u0440\u043e\u043c\u043a\u0438')),
                ('lightning', models.ManyToManyField(blank=True, to='home.Lightning', verbose_name='\u041e\u0441\u0432\u044f\u0449\u0435\u043d\u0438\u0435')),
                ('material', models.ManyToManyField(blank=True, to='home.Material', verbose_name='\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b')),
                ('preview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.AlbumImage', verbose_name='\u041e\u0431\u043b\u043e\u0436\u043a\u0430/\u041f\u0440\u0435\u0432\u044c\u044e')),
                ('proportions', models.ManyToManyField(blank=True, to='home.Proportion', verbose_name='\u041f\u0440\u043e\u043f\u043e\u0440\u0446\u0438\u0438')),
                ('section', models.ForeignKey(blank=True, help_text='\u0412\u044b\u0431\u0438\u0440\u0435\u0442\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044e \u043e\u0431\u0440\u0430\u0437\u0446\u0430..', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_of_product', to='catalog.CategorySection', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0430')),
                ('visualisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_visualisation', to='album.AlbumImage', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0432\u0438\u0437\u0443\u0430\u043b\u0438\u0437\u0438\u0440\u0443\u044e\u0449\u0438\u0435 \u043f\u0440\u043e\u0434\u0443\u043a\u0442')),
            ],
            options={
                'db_table': 'collection_products',
                'verbose_name': '\u041f\u0440\u043e\u0434\u0443\u043a\u0442',
                'verbose_name_plural': '\u041f\u0440\u043e\u0434\u0443\u043a\u0442',
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_items',
            field=models.ManyToManyField(related_name='collection_items', to='catalog.Product', verbose_name='\u041f\u0440\u0435\u0434\u043c\u0435\u0442\u044b \u043a\u043e\u043b\u043b\u0435\u043a\u0446\u0438\u0438'),
        ),
        migrations.AddField(
            model_name='collection',
            name='preview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.AlbumImage', verbose_name='\u041e\u0431\u043b\u043e\u0436\u043a\u0430/\u041f\u0440\u0435\u0432\u044c\u044e'),
        ),
        migrations.AddField(
            model_name='category',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text='\u0412\u044b\u0431\u0438\u0440\u0435\u0442\u0435 \u043a\u043e\u043b\u0435\u043a\u0446\u0438\u0438, \u043a\u043e\u0442\u043e\u0440\u044b\u0435 \u0431\u0443\u0434\u0443\u0442 \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c\u0441\u044f \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435 \u0432\u044b\u0431\u0440\u0430\u043d\u043d\u043e\u0439 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u043c \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438.', related_name='collections_of_category', to='catalog.Collection', verbose_name='\u041a\u043e\u043b\u043b\u0435\u043a\u0446\u0438\u0438 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0439'),
        ),
        migrations.AddField(
            model_name='category',
            name='preview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.AlbumImage', verbose_name='\u041e\u0431\u043b\u043e\u0436\u043a\u0430/\u041f\u0440\u0435\u0432\u044c\u044e'),
        ),
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(blank=True, help_text="\u0412\u044b\u0431\u0438\u0440\u0435\u0442\u0435 \u043e\u0442\u0434\u0435\u043b\u044c\u043d\u044b\u0435 \u043f\u0440\u0435\u0434\u043c\u0435\u0442\u044b \u043e\u0442\u043d\u043e\u0441\u044f\u0449\u0438\u0435\u0441\u044f \u043a \u044d\u0442\u043e\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438, \u043a\u043e\u0442\u043e\u0440\u044b\u0435 \u0431\u0443\u0434\u0443\u0442 \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c\u0441\u044f \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435 \u0432\u044b\u0431\u0440\u0430\u043d\u043d\u043e\u0439 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u043c \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u0432 \u0440\u0430\u0437\u0434\u0435\u043b\u0435 '\u041e\u0442\u0434\u0435\u043b\u044c\u043d\u044b\u0435 \u043f\u0440\u0435\u0434\u043c\u0435\u0442\u044b'.", related_name='products_of_category', to='catalog.Product', verbose_name='\u041e\u0442\u0434\u0435\u043b\u044c\u043d\u044b\u0435 \u043f\u0440\u0435\u0434\u043c\u0435\u0442\u044b'),
        ),
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.ForeignKey(help_text='\u041f\u0440\u0438\u043d\u0430\u0434\u043b\u0435\u0436\u043d\u043e\u0441\u0442\u044c \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u043a \u043e\u0434\u043d\u043e\u0439 \u0438\u0437 \u0441\u0435\u043a\u0446\u0438\u0439 "\u0424\u043e\u0440\u043c\u0430", "\u0421\u0438\u0441\u0442\u0435\u043c\u044b", "\u041e\u0441\u0432\u044f\u0449\u0435\u043d\u0438\u0435" \u0438 \u0442.\u043f. <br/>\u0414\u043b\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0430.', on_delete=django.db.models.deletion.CASCADE, related_name='group_of_category', to='catalog.CategorySection', verbose_name='\u0421\u0435\u043a\u0446\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='brand',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='\u0412\u044b\u0431\u0438\u0440\u0435\u0442\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438, \u043a\u043e\u0442\u043e\u0440\u044b\u0435 \u0431\u0443\u0434\u0443\u0442 \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c\u0441\u044f \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435 \u0432\u044b\u0431\u0440\u0430\u043d\u043d\u043e\u0433\u043e \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u043c \u0431\u0440\u0435\u043d\u0434\u0430.', related_name='categories_of_brand', to='catalog.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u0431\u0440\u0435\u043d\u0434\u0430'),
        ),
        migrations.AddField(
            model_name='brand',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text='\u0412\u044b\u0431\u0438\u0440\u0435\u0442\u0435 \u043a\u043e\u043b\u0435\u043a\u0446\u0438\u0438, \u043a\u043e\u0442\u043e\u0440\u044b\u0435 \u0431\u0443\u0434\u0443\u0442 \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c\u0441\u044f \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435 \u0432\u044b\u0431\u0440\u0430\u043d\u043d\u043e\u0433\u043e \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u043c \u0431\u0440\u0435\u043d\u0434\u0430.', related_name='collections_of_brand', to='catalog.Collection', verbose_name='\u041a\u043e\u043b\u043b\u0435\u043a\u0446\u0438\u0438 \u0431\u0440\u0435\u043d\u0434\u0430'),
        ),
        migrations.AddField(
            model_name='brand',
            name='preview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.AlbumImage', verbose_name='\u041e\u0431\u043b\u043e\u0436\u043a\u0430/\u041f\u0440\u0435\u0432\u044c\u044e'),
        ),
        migrations.AddField(
            model_name='brand',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='\u0412\u044b\u0431\u0438\u0440\u0435\u0442\u0435 \u043e\u0431\u0440\u0430\u0437\u0446\u044b, \u043a\u043e\u0442\u043e\u0440\u044b\u0435 \u0431\u0443\u0434\u0443\u0442 \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c\u0441\u044f \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435 \u0432\u044b\u0431\u0440\u0430\u043d\u043d\u043e\u0433\u043e \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u043c \u0431\u0440\u0435\u043d\u0434\u0430.', related_name='products_of_brand', to='catalog.Product', verbose_name='\u041e\u0431\u0440\u0430\u0437\u0446\u044b \u0431\u0440\u0435\u043d\u0434\u0430'),
        ),
    ]
