# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180125_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Выбирете категории, которые будут отображаться на странице выбранного пользователем бренда.', related_name='categories_of_brand', to='catalog.Category', verbose_name='Категории бренда'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text='Выбирете колекции, которые будут отображаться на странице выбранного пользователем бренда.', related_name='categories_of_brand', to='catalog.Collection', verbose_name='Коллекции бренда'),
        ),
        migrations.AlterField(
            model_name='category',
            name='brands',
            field=models.ManyToManyField(blank=True, help_text='Выбирете бренды, которые будут отображаться в выбранной пользователем категории.', related_name='categories_of_brand', to='catalog.Brand', verbose_name='Категории бренда'),
        ),
    ]
