# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180125_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text='Выбирете колекции, которые будут отображаться на странице выбранной пользователем категории.', related_name='collections_of_category', to='catalog.Collection', verbose_name='Коллекции категорий'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text='Выбирете колекции, которые будут отображаться на странице выбранного пользователем бренда.', related_name='collections_of_brand', to='catalog.Collection', verbose_name='Коллекции бренда'),
        ),
        migrations.AlterField(
            model_name='category',
            name='brands',
            field=models.ManyToManyField(blank=True, help_text='Выбирете бренды, которые будут отображаться на странице выбранной пользователем категории.', related_name='categories_of_brand', to='catalog.Brand', verbose_name='Категории бренда'),
        ),
    ]
