# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20180125_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(blank=True, help_text="Выбирете отдельные предметы относящиеся к этой категории, которые будут отображаться на странице выбранной пользователем категории в разделе 'Отдельные предметы'.", related_name='products_of_category', to='catalog.Product', verbose_name='Отдельные предметы'),
        ),
        migrations.AlterField(
            model_name='category',
            name='section',
            field=models.ForeignKey(help_text='Принадлежность категории к одной из секций "Форма", "Системы", "Освящение" и т.п. <br/>Для страницы каталога.', on_delete=django.db.models.deletion.CASCADE, related_name='group_of_category', to='catalog.CategorySection', verbose_name='Секция'),
        ),
    ]
