# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20180125_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta',
            field=models.TextField(blank=True, max_length=350, null=True, verbose_name='META-описание страницы'),
        ),
        migrations.AddField(
            model_name='product',
            name='page_title',
            field=models.CharField(blank=True, help_text='Название страницы во вкладке', max_length=100, null=True, verbose_name='Заголовок'),
        ),
    ]
