# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-26 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20180125_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='brands',
            field=models.ManyToManyField(blank=True, help_text='Выбирете бренды, которые будут отображаться на странице выбранной пользователем категории.', related_name='brands_of_category', to='catalog.Brand', verbose_name='Бренды категории'),
        ),
    ]
