# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-26 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20180126_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Выбирете бренд, который относится к этой коллекции. Она может быть независимой.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_of_collection', to='catalog.Brand', verbose_name='Бренд коллекции'),
        ),
    ]
