# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20180126_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Выбирете бренд, который относится к этому образцу.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_of_product', to='catalog.Brand', verbose_name='Бренд образца'),
        ),
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Выбирете категорию образца..', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_of_product', to='catalog.CategorySection', verbose_name='Категория продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='album',
            field=models.ForeignKey(blank=True, help_text='Альбом для слайдов.', null=True, on_delete=django.db.models.deletion.CASCADE, to='album.Album', verbose_name='Презентационный альбом'),
        ),
        migrations.AlterField(
            model_name='product',
            name='visualisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_visualisation', to='album.AlbumImage', verbose_name='Изображение визуализирующие продукт'),
        ),
    ]
