# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20180208_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorysection',
            options={'verbose_name': 'Секция', 'verbose_name_plural': 'Секции'},
        ),
        migrations.AddField(
            model_name='brand',
            name='is_shown',
            field=models.BooleanField(default=True, verbose_name='Отобрзить в каталоге?'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_shown',
            field=models.BooleanField(default=True, verbose_name='Отобрзить в каталоге?'),
        ),
        migrations.AddField(
            model_name='collection',
            name='is_shown',
            field=models.BooleanField(default=True, verbose_name='Отобрзить в каталоге?'),
        ),
    ]
