# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_product_is_shown'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='angle_of_bend',
            field=models.IntegerField(blank=True, help_text='Целочисленное значение, к примеру: 30', null=True, verbose_name='Минимальный угол загиба'),
        ),
        migrations.AddField(
            model_name='product',
            name='diameter',
            field=models.CharField(blank=True, help_text='Пример: от 50 мм до 150 мм', max_length=100, null=True, verbose_name='Диаметр окружности'),
        ),
        migrations.AddField(
            model_name='product',
            name='step_between_panels',
            field=models.CharField(blank=True, help_text='Пример: от 100 мм до 1000 мм', max_length=100, null=True, verbose_name='Шаг между панелями'),
        ),
    ]
