# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-19 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_proportion'),
        ('catalog', '0017_product_ceil_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='proportions',
            field=models.ManyToManyField(blank=True, to='home.Proportion', verbose_name='Пропорции'),
        ),
    ]
