# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-13 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_product_proportions'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Выбирете образцы, которые будут отображаться на странице выбранного пользователем бренда.', related_name='products_of_brand', to='catalog.Product', verbose_name='Образцы бренда'),
        ),
    ]
