# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-15 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_brand_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Выбирете категорию, к который относится эта коллекция.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_of_collection', to='catalog.Category', verbose_name='Категория коллекции'),
        ),
    ]
