# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20180516_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='meta',
            field=models.TextField(blank=True, max_length=350, null=True, verbose_name='META-описание страницы'),
        ),
        migrations.AddField(
            model_name='brand',
            name='page_title',
            field=models.CharField(blank=True, help_text='Название страницы во вкладке', max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta',
            field=models.TextField(blank=True, max_length=350, null=True, verbose_name='META-описание страницы'),
        ),
        migrations.AddField(
            model_name='category',
            name='page_title',
            field=models.CharField(blank=True, help_text='Название страницы во вкладке', max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='collection',
            name='meta',
            field=models.TextField(blank=True, max_length=350, null=True, verbose_name='META-описание страницы'),
        ),
        migrations.AddField(
            model_name='collection',
            name='page_title',
            field=models.CharField(blank=True, help_text='Название страницы во вкладке', max_length=100, null=True, verbose_name='Заголовок'),
        ),
    ]
