# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20180627_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='meta',
            field=models.TextField(blank=True, max_length=350, null=True, verbose_name='META-описание страницы'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta',
            field=models.TextField(blank=True, max_length=350, null=True, verbose_name='META-описание страницы'),
        ),
        migrations.AddField(
            model_name='collection',
            name='meta',
            field=models.TextField(blank=True, max_length=350, null=True, verbose_name='META-описание страницы'),
        ),
    ]
