# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-05-12 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('last_name', models.CharField(max_length=36, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('first_name', models.CharField(max_length=32, verbose_name='\u0418\u043c\u044f')),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('phone_number', models.CharField(blank=True, max_length=26, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('requisites', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0420\u0435\u043a\u0432\u0438\u0437\u0438\u0442\u044b')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440')),
            ],
            options={
                'db_table': 'site_consumers',
                'verbose_name': '\u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a',
                'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('width', models.CharField(blank=True, help_text='\u041f\u0440\u0438\u043c\u0435\u0440: \u041e\u0442 10 \u043c\u043c \u0434\u043e 250 \u043c\u043c', max_length=100, null=True, verbose_name='\u0428\u0438\u0440\u0438\u043d\u0430')),
                ('height', models.CharField(blank=True, help_text='\u041f\u0440\u0438\u043c\u0435\u0440: 8\u043c\u043c', max_length=100, null=True, verbose_name='\u0412\u044b\u0441\u043e\u0442\u0430')),
                ('length', models.CharField(blank=True, help_text='\u041f\u0440\u0438\u043c\u0435\u0440: \u043e\u0442 1\u043c \u0434\u043e 10\u043c', max_length=100, null=True, verbose_name='\u0414\u043b\u0438\u043d\u0430')),
                ('thickness', models.CharField(blank=True, help_text='\u041f\u0440\u0438\u043c\u0435\u0440: \u043e\u0442 1 \u043c\u043c \u0434\u043e 1,5 \u043c\u043c', max_length=100, null=True, verbose_name='\u0422\u043e\u043b\u0449\u0438\u043d\u0430')),
                ('step_between_panels', models.CharField(blank=True, help_text='\u041f\u0440\u0438\u043c\u0435\u0440: \u043e\u0442 100 \u043c\u043c \u0434\u043e 1000 \u043c\u043c', max_length=100, null=True, verbose_name='\u0428\u0430\u0433 \u043c\u0435\u0436\u0434\u0443 \u043f\u0430\u043d\u0435\u043b\u044f\u043c\u0438')),
                ('angle_of_bend', models.IntegerField(blank=True, help_text='\u0426\u0435\u043b\u043e\u0447\u0438\u0441\u043b\u0435\u043d\u043d\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435, \u043a \u043f\u0440\u0438\u043c\u0435\u0440\u0443: 30', null=True, verbose_name='\u041c\u0438\u043d\u0438\u043c\u0430\u043b\u044c\u043d\u044b\u0439 \u0443\u0433\u043e\u043b \u0437\u0430\u0433\u0438\u0431\u0430')),
                ('diameter', models.CharField(blank=True, help_text='\u041f\u0440\u0438\u043c\u0435\u0440: \u043e\u0442 50 \u043c\u043c \u0434\u043e 150 \u043c\u043c', max_length=100, null=True, verbose_name='\u0414\u0438\u0430\u043c\u0435\u0442\u0440 \u043e\u043a\u0440\u0443\u0436\u043d\u043e\u0441\u0442\u0438')),
                ('ceil_size', models.CharField(blank=True, help_text='\u041f\u0440\u0438\u043c\u0435\u0440: \u043e\u0442 5\u043c\u043c \u0434\u043e 50 \u043c\u043c', max_length=100, null=True, verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440 \u044f\u0447\u0435\u0435\u043a')),
                ('quantity', models.IntegerField(default=1, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('full_price', models.DecimalField(blank=True, decimal_places=2, help_text='\u0420\u0430\u0441\u0447\u0438\u0442\u044b\u0432\u0430\u0435\u0442\u0441\u044f \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438. \u0417\u0430\u0432\u0438\u0441\u0438\u0442 \u043e\u0442 \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043d\u043e\u0439 \u0446\u0435\u043d\u044b \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0430 \u0438 \u043e\u0444\u043e\u0440\u043c\u043b\u0435\u043d\u043d\u043e\u0433\u043e \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u0430.', max_digits=18, null=True, verbose_name='\u041e\u0431\u0449\u0430\u044f \u0446\u0435\u043d\u0430')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440')),
                ('acoustics', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Acoustics', verbose_name='\u0410\u043a\u0443\u0441\u0442\u0438\u043a\u0430')),
                ('colors', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Color', verbose_name='\u0426\u0432\u0435\u0442')),
                ('combustibility', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Combustibility', verbose_name='\u0413\u043e\u0440\u044e\u0447\u0435\u0441\u0442\u044c')),
                ('edges', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Edge', verbose_name='\u041a\u0440\u043e\u043c\u043a\u0438')),
                ('lightning', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Lightning', verbose_name='\u041e\u0441\u0432\u044f\u0449\u0435\u043d\u0438\u0435')),
                ('material', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Material', verbose_name='\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_product', to='catalog.Product', verbose_name='\u041f\u0440\u043e\u0434\u0443\u043a\u0442')),
                ('proportions', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Proportion', verbose_name='\u041f\u0440\u043e\u043f\u043e\u0440\u0446\u0438\u0438')),
            ],
            options={
                'db_table': 'consumers_ordered_products',
                'verbose_name': '\u041e\u0444\u043e\u0440\u043c\u043b\u0435\u043d\u043d\u044b\u0439 \u043f\u0440\u043e\u0434\u0443\u043a\u0442',
                'verbose_name_plural': '\u041e\u0444\u043e\u0440\u043c\u043b\u0435\u043d\u043d\u044b\u0435 \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u044b',
            },
        ),
    ]
