# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180125_0938'),
        ('personal_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='acoustics',
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='acoustics',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Acoustics', verbose_name='Акустика'),
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='colors',
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='colors',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Color', verbose_name='Цвета'),
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='combustibility',
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='combustibility',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Combustibility', verbose_name='Горючесть'),
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='edges',
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='edges',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Edge', verbose_name='Кромки'),
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='lightning',
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='lightning',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Lightning', verbose_name='Освящение'),
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='material',
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='material',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Material', verbose_name='Материал'),
        ),
    ]
