# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0002_auto_20180125_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='colors',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Color', verbose_name='Цвет'),
        ),
    ]
