# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0003_auto_20180125_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumer',
            options={'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчики'},
        ),
        migrations.AlterModelOptions(
            name='orderedproduct',
            options={'verbose_name': 'Оформленный продукт', 'verbose_name_plural': 'Оформленные продукты'},
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='full_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Расчитывается автоматически. Зависит от установленной цены продукта и оформленного количества.', max_digits=18, null=True, verbose_name='Общая цена'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
