# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0004_auto_20180125_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=26, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='requisites',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Реквизиты'),
        ),
    ]
