# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-26 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0005_auto_20180125_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='Идентификатор'),
        ),
    ]
