# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-11 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0006_orderedproduct_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='acoustics',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Acoustics', verbose_name='Акустика'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='colors',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='combustibility',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Combustibility', verbose_name='Горючесть'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='edges',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Edge', verbose_name='Кромки'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='lightning',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Lightning', verbose_name='Освящение'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='material',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Material', verbose_name='Материал'),
        ),
    ]
